#ifndef _HYPRAID_IOCTL_H_
#define _HYPRAID_IOCTL_H_

struct hypraid_ioctl
{
    int uvalue[100];
    int kvalue[100];
};

enum
{
    _HYPRAID_GET_PRIORITY,
    _HYPRAID_BLOCK_REPLACEMENT,
    _HYPRAID_BLOCK_REPLACEMENT_AREA,
    _HYPRAID_INSERT_AREA,
    _HYPRAID_PRINT_AREA,
    _HYPRAID_DELETE_AREA,
    _HYPRAID_SET_MODE,
    _HYPRAID_REPLACEMENT_TEST,
    _HYPRAID_TRANSFORM_BLOCK,
    HYPRAID_IOCTL_MAX
};

#define HYPRAID_IOCTL_MAGIC_KEY 'h'
#define HYPRAID_NAME "/dev/mapper/hypraid"

#define HYPRAID_GET_PRIORITY _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_GET_PRIORITY, struct hypraid_ioctl)
#define HYPRAID_BLOCK_REPLACEMENT _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_BLOCK_REPLACEMENT, struct hypraid_ioctl)
#define HYPRAID_BLOCK_REPLACEMENT_AREA _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_BLOCK_REPLACEMENT_AREA, struct hypraid_ioctl)
#define HYPRAID_INSERT_AREA _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_INSERT_AREA, struct hypraid_ioctl)
#define HYPRAID_PRINT_AREA _IO(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_PRINT_AREA)
#define HYPRAID_DELETE_AREA _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_DELETE_AREA, struct hypraid_ioctl)
#define HYPRAID_REPLACEMENT_TEST _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_REPLACEMENT_TEST, struct hypraid_ioctl)
#define HYPRAID_TRANSFORM_BLOCK _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_TRANSFORM_BLOCK, struct hypraid_ioctl)
#define HYPRAID_SET_MODE _IOWR(HYPRAID_IOCTL_MAGIC_KEY, _HYPRAID_SET_MODE, struct hypraid_ioctl)

#endif
